from enum import Enum


class GENERAL_MESSAGE(Enum):  # Used only Client and Server
    SHUTDOWN = -1
    OK = 0
    FILE_TRANSFER_START = 1
    FILE_TRANSFER_END = 2
    CLIENT_REGISTER = 3


class MANAGER_MESSAGE(Enum):
    CONFIG = 4
    CREATE_NODE = 5
    REQUEST_NODE_SERVER_DATA = 6
    BROADCAST_NODE_SERVER_DATA = 7
    REPORT_STATUS = 8
    REQUEST_STEP = 9
    START_NODES = 10
    STOP_NODES = 11
    REQUEST_SAVING = 12
    REQUEST_GATHER = 13
    REQUEST_COLLECT = 14
    REQUEST_CODE_LOAD = 15
    CLUSTER_SHUTDOWN = 16


class WORKER_MESSAGE(Enum):
    PACKAGE_LOADED = 17
    REGISTER = 18
    DEREGISTER = 19
    REPORT_NODE_SERVER_DATA = 20
    BROADCAST_NODE_SERVER_DATA = 21
    REPORT_NODES_STATUS = 22
    COMPLETE_BROADCAST = 23
    REQUEST_STEP = 24
    REQUEST_GATHER = 25
    REQUEST_SAVING = 26
    REPORT_GATHER = 27
    REPORT_NODE_SAVING = 28
    START_NODES = 29
    STOP_NODES = 30
    TRANSFER_COMPLETE = 31


class NODE_MESSAGE(Enum):
    STATUS = 32
    REPORT_GATHER = 33
    REPORT_SAVING = 34
