from enum import Enum


class GENERAL_MESSAGE(Enum):  # Used only Client and Server
    SHUTDOWN = -1
    OK = 0
    FILE_TRANSFER_START = 1
    FILE_TRANSFER_END = 2
    CLIENT_REGISTER = 3


class MANAGER_MESSAGE(Enum):
    CONFIG = 4
    CREATE_NODE = 5
    REQUEST_NODE_SERVER_DATA = 6
    BROADCAST_NODE_SERVER_DATA = 7
    REPORT_STATUS = 8
    REQUEST_STEP = 9
    START_NODES = 10
    STOP_NODES = 11
    REQUEST_GATHER = 12
    REQUEST_COLLECT = 13
    REQUEST_CODE_LOAD = 14
    CLUSTER_SHUTDOWN = 15


class WORKER_MESSAGE(Enum):
    PACKAGE_LOADED = 16
    REGISTER = 17
    DEREGISTER = 18
    REPORT_NODE_SERVER_DATA = 19
    BROADCAST_NODE_SERVER_DATA = 20
    REPORT_NODES_STATUS = 21
    COMPLETE_BROADCAST = 22
    REQUEST_STEP = 23
    REQUEST_GATHER = 24
    REPORT_GATHER = 25
    START_NODES = 26
    STOP_NODES = 27
    TRANSFER_COMPLETE = 28


class NODE_MESSAGE(Enum):
    STATUS = 29
    REPORT_GATHER = 30
