@startuml
skinparam componentStyle rectangle
/' skinparam monochrome reverse '/
/' left to right direction '/

' Creating the instances of the components
node "Data Stream 1" as DS1
node "Data Stream 2" as DS2
node "Data Stream 3" as DS3

' Pre-processing 
frame "Pre-Fusion Processing" {
    [Process 1]
    [Process 2]
}

node "Data Stream 1*" as DS1_
node "Data Stream 2*" as DS2_

component Collector {
    [Time alignment]
}

component Analyzer {
    [Session]
    frame "Post-Fusion Processing" as PFP {
        [Process 3]
        [Process 4]
        [Process 5]
    }
}

' Applying pre-sync processing
DS1 --> [Process 1] 
DS2 --> [Process 2] 
[Process 1] --> DS1_
[Process 2] --> DS2_

' Passing the data to collector
DS1_ --> Collector
DS2_ --> Collector
DS3 ----> Collector

' The collector feeds analyzer
[Time alignment] --> Session

' Showing the movement inside the analyzer
[Process 3] --> [Process 5]
[Process 4] --> [Process 5]
[Session] -> PFP
PFP -> [Session]

@enduml
